### PR TITLE
Added Foundation tabs and accordion functionality

### PR DESCRIPTION
**Pull request by jayarnielsen**
Added support for foundation tabs and accordions:
http://foundation.zurb.com/docs/components/accordion.html
http://foundation.zurb.com/docs/components/tabs.html

Extends the bootstrap3 implementation in crispy forms.

### CODE REVIEW

**Comment by sveetch** [comment]
It's a big addon, i have to review it in the demo and probably see to split layout components because the layout.py is getting a little big now..

Will see it this week end

**Comment by sveetch** [comment]
Ok this is merged but i did have to do a lot of works because there was a lot of issues to deal with input error within tabs and accordion, also i renamed the layout object for consistence (as the Bootstrap name does not mean anything with Foundation).

I still have some details to do before releasing this as the 0.5.0, probably this week.

**Comment by jayarnielsen** [comment]
Nice! Thanks for that. This plugin is incredible.

**Comment by sveetch** [comment]
Ok it's released, also the demo app has been updated.

**Pull request merged**
