### PR TITLE
Added support for django-crispy-forms 2.0

### PR DESCRIPTION
**Pull request by sprda**
New version of django-crispy-forms 2.0 breaks the package with the following render() error
TypeError: render() missing 1 required positional argument: 'context'

see https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/2.0
<snip>
The uni-form template pack allowed for rendering of templates using a default or inline layout. As the uni-form template
pack has been removed support for this has also been removed. This has resulted in the following BREAKING changes.

    The form_style attribute of FormHelper is removed.
    The form_style positional argument to render_field() is removed.
    The form_style positional argument to the render() method of all LayoutObjects is removed.

Audit for use of render() and render_field() due to the removal of the form_style positional argument is therefore
required. For example:

# django-crispy-forms 1.x
html = my_layout_object.render(form, form_style, context)
# django-crispy-forms 2.x
html = my_layout_object.render(form, context)
</snip>

I've bumped the version to 2.0 simply to come in-line with django-crispy-forms

### CODE REVIEW

**Comment by sprda** [comment]
As the pull request stands, it passed python3.9 and all changes are included in the the PR.  I also reviewed issue #50 (about a pointer reference) but did not run into that problem.   

Per the crispy-forms latest documents it references 2.0 installations. https://django-crispy-forms.readthedocs.io/en/latest/install.html#installing-django-crispy-forms states the template packs were broken out to their separate package install. Similar to crispy-forms-foundation, from what it sounds.

From the tox run:
<snip>
  py38-django320: SKIP (0.02 seconds)
  py38-django400: SKIP (0.00 seconds)
  py38-django410: SKIP (0.00 seconds)
  py38-django420: SKIP (0.00 seconds)
  py39-django320: OK (5.67=setup[2.25]+cmd[1.21,2.21] seconds)
  py39-django400: OK (4.66=setup[1.43]+cmd[1.20,2.02] seconds)
  py39-django410: OK (4.73=setup[1.51]+cmd[1.30,1.92] seconds)
  py39-django420: OK (4.63=setup[1.44]+cmd[1.21,1.98] seconds)
  py310-django320: SKIP (0.01 seconds)
  py310-django400: SKIP (0.00 seconds)
  py310-django410: SKIP (0.00 seconds)
  py310-django420: SKIP (0.00 seconds)
  py311-django320: SKIP (0.00 seconds)
  py311-django400: SKIP (0.00 seconds)
  py311-django410: SKIP (0.00 seconds)
  py311-django420: SKIP (0.05 seconds)
  congratulations :) (19.93 seconds)


$ pip freeze
cachetools==5.3.1
chardet==5.1.0
colorama==0.4.6
distlib==0.3.6
filelock==3.12.0
packaging==23.1
platformdirs==3.5.1
pluggy==1.0.0
pyproject_api==1.5.1
tomli==2.0.1
tox==4.5.2
virtualenv==20.23.0

**Comment by sveetch** [comment]
> As the pull request stands, it passed python3.9 and all changes are included in the the PR. I also reviewed issue #50 (about a pointer reference) but did not run into that problem.

Ok nice.

> Per the crispy-forms latest documents it references 2.0 installations. [...] states the template packs were broken out to their separate package install.

Ok i know, i was just wondering if finally it worked well with the default template pack shipped in crispy-form itself, since the foundation layout objects stands on the ones from crispy-forms. Since i'm not sure anymore we patched every templates, i was not sure if it rendered with our requirements that does not include the bootstrap ones, i mean do we have to append the bootstrap template pack to the requirement or not.

**Comment by sprda** [comment]
> Ok i know, i was just wondering if finally it worked well with the default template pack shipped in crispy-form itself (that was the bootstrap layer), since the foundation layout objects stands on the ones from crispy-forms. Since i'm not sure anymore we patched every templates, i was not sure if it rendered with our requirements that does not include the bootstrap ones, i mean do we have to append the bootstrap template pack to the requirement or not.

Our app uses only foundation (no bootstrap), none of the other crispy-forms template packs were installed.  I just tested a few form pages and they seem to be rendering correctly.  Just the standard configs...

setting.py:
INSTALLED_APPS = [
...
    'crispy_forms',
    'crispy_forms_foundation',
...
]
CRISPY_TEMPLATE_PACK = 'foundation-6'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'foundation-6'

------
one of our apps:
from crispy_forms_foundation.layout import (
    Layout, Fieldset, Field, SwitchField,
    ButtonGroup, ButtonReset, ButtonSubmit,
    HTML,
    Row, Column,
)
----
maybe we're not using/executing the code/functions you're concerned with..I'm willing to code review if you want to point me in the direction where you think an issue may lay.

**Comment by sveetch** [comment]
@sprda then it seems ok for me, for truth i don't used crispy since last year and i don't use anymore Foundation, so i was not really sure. Let me this weekend to get your branch and pass quality tasks on it before to merge and release.

**Comment by sveetch** [comment]
This has been merged in 1.0.0. 

Note than i fixed package version to 1.0 instead of 2.0, since it depends from both crispy-forms and Foundation, it can not be tied to a dependency so it have its own release scheme.

Thanks for your work.

**Pull request merged**
